open_manipulator_joint_state_controller: 
    type: "joint_state_controller/JointStateController"
    publish_rate: 100 

open_manipulator_arm_position_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
    - joint6
    gains: 
        joint1: {p: 10, d: 1, i: 0, i_clamp: 1}
        joint2: {p: 10, d: 1, i: 0, i_clamp: 1}
        joint3: {p: 10, d: 1, i: 0, i_clamp: 1}
        joint4: {p: 10, d: 1, i: 0, i_clamp: 1}
        joint5: {p: 10, d: 1, i: 0, i_clamp: 1}
        joint6: {p: 10, d: 1, i: 0, i_clamp: 1}

open_manipulator_gripper_position_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
    - gripper
    gains: 
        gripper: {p: 10, d: 1, i: 0, i_clamp: 1}
